print("It is just you and I in this class")
print("We are learning Python together")
print("Let's make the most of it!")
print("Welcome to Class 2!")
print("This is an exciting journey ahead")
print("Stay curious and keep exploring!")
print("Glad we figured this out together! Especialy the recording part")
print("Looking forward to more learning sessions with you!")
print("Remember to practice what we learn")
print("Consistency is key to mastering Python")
print("Collaboration is key to success")
print("Let's help each other grow")
print("Don't hesitate to ask questions")
print("Sharing knowledge makes us stronger")
print("Happy Coding!!!")