print("I love programming...")
print("Programming is fun!!!...")
print("This is an interesting class...")
print("I am learning Python...")
print ("Python is a versatile language...")
print ("I am learning git and versioning")
print("Collaboration is important...")
print("Let's work together to build something amazing!")